[package]
name = "stars"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true

[dependencies]
argh = "0.1"
console = "0.15"
indicatif = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tap = "1.0"
ureq = "2.4"
url = { version = "2.2", features = ["serde"] }
which = "4.2"
